/* automatically generated by rust-bindgen */

pub const __INTEL_MKL_BUILD_DATE : u32 = 20180128;
pub const __INTEL_MKL__ : u32 = 2018;
pub const __INTEL_MKL_MINOR__ : u32 = 0;
pub const __INTEL_MKL_UPDATE__ : u32 = 2;
pub const INTEL_MKL_VERSION : u32 = 20180002 ;